# Generated by Django 4.2.21 on 2025-06-22 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=128)),
                ('role', models.CharField(default='user', max_length=10)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'Language',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_type', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'db_table': 'Pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('sexual_orientation', models.CharField(blank=True, max_length=8, null=True)),
                ('pronouns', models.CharField(blank=True, max_length=9, null=True)),
                ('height_cm', models.IntegerField(blank=True, null=True)),
                ('body_type', models.CharField(blank=True, max_length=14, null=True)),
                ('education_level', models.CharField(blank=True, max_length=16, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('religion', models.CharField(blank=True, max_length=9, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=14, null=True)),
                ('politics', models.CharField(blank=True, max_length=13, null=True)),
                ('smoking', models.CharField(blank=True, max_length=9, null=True)),
                ('drinking', models.CharField(blank=True, max_length=9, null=True)),
                ('drug_use', models.CharField(blank=True, max_length=9, null=True)),
                ('has_kids', models.IntegerField(blank=True, null=True)),
                ('wants_kids', models.CharField(blank=True, max_length=15, null=True)),
                ('zodiac_sign', models.CharField(blank=True, max_length=11, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
                ('relationship_goals', models.CharField(blank=True, max_length=23, null=True)),
            ],
            options={
                'db_table': 'Profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('image_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ProfileImage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profilelanguage',
            fields=[
                ('profile_language_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ProfileLanguage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profilepet',
            fields=[
                ('profile_pet_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ProfilePet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.CharField(db_column='subscription_id', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, help_text='JSON field storing enabled features', null=True)),
                ('billing_cycle', models.CharField(choices=[('1week', '1 Week'), ('1month', '1 Month'), ('3month', '3 Months')], db_column='billing_cycle', max_length=6)),
                ('started_at', models.DateTimeField(db_column='started_at')),
                ('expires_at', models.DateTimeField(db_column='expires_at')),
                ('auto_renew', models.IntegerField(blank=True, db_column='auto_renew', null=True)),
                ('status', models.CharField(blank=True, db_column='status', max_length=20, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, db_column='stripe_subscription_id', max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, db_column='stripe_customer_id', max_length=255, null=True)),
                ('stripe_price_id', models.CharField(blank=True, db_column='stripe_price_id', max_length=100, null=True)),
                ('stripe_session_id', models.CharField(blank=True, db_column='stripe_session_id', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Subscription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('preference_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_age_min', models.IntegerField()),
                ('preferred_age_max', models.IntegerField()),
                ('preferred_distance_km', models.IntegerField()),
                ('preferred_height_min', models.IntegerField(blank=True, null=True)),
                ('preferred_height_max', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('profile_id_fk', models.OneToOneField(db_column='profile_id_fk', on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
            options={
                'db_table': 'Preferences',
            },
        ),
        migrations.CreateModel(
            name='PreferencesZodiac',
            fields=[
                ('preferences_zodiac_id', models.AutoField(primary_key=True, serialize=False)),
                ('zodiac_type', models.CharField(choices=[('aries', 'Aries'), ('taurus', 'Taurus'), ('gemini', 'Gemini'), ('cancer', 'Cancer'), ('leo', 'Leo'), ('virgo', 'Virgo'), ('libra', 'Libra'), ('scorpio', 'Scorpio'), ('sagittarius', 'Sagittarius'), ('capricorn', 'Capricorn'), ('aquarius', 'Aquarius'), ('pisces', 'Pisces')], max_length=20)),
                ('preference_id_fk', models.OneToOneField(db_column='preference_id_fk', on_delete=django.db.models.deletion.CASCADE, to='authentication.preferences')),
            ],
            options={
                'db_table': 'PreferencesZodiac',
            },
        ),
        migrations.CreateModel(
            name='PreferencesWantsKids',
            fields=[
                ('preferences_wantskids_id', models.AutoField(primary_key=True, serialize=False)),
                ('wants_kids_type', models.CharField(choices=[("don't want kids", "Don't Want Kids"), ('open to kids', 'Open to Kids'), ('want kids', 'Want Kids')], max_length=30)),
                ('preference_id_fk', models.OneToOneField(db_column='preference_id_fk', on_delete=django.db.models.deletion.CASCADE, to='authentication.preferences')),
            ],
            options={
                'db_table': 'PreferencesWantsKids',
            },
        ),
        migrations.CreateModel(
            name='PreferencesSmoking',
            fields=[
                ('preferences_smoking_id', models.AutoField(primary_key=True, serialize=False)),
                ('smoking_type', models.CharField(choices=[('yes', 'Yes'), ('sometimes', 'Sometimes'), ('no', 'No')], max_length=10)),
                ('preference_id_fk', models.OneToOneField(db_column='preference_id_fk', on_delete=django.db.models.deletion.CASCADE, to='authentication.preferences')),
            ],
            options={
                'db_table': 'PreferencesSmoking',
            },
        ),
        migrations.CreateModel(
            name='PreferencesReligion',
            fields=[
                ('preferences_religion_id', models.AutoField(primary_key=True, serialize=False)),
                ('religion_type', models.CharField(choices=[('agnostic', 'Agnostic'), ('atheist', 'Atheist'), ('buddhist', 'Buddhist'), ('catholic', 'Catholic'), ('christian', 'Christian'), ('hindu', 'Hindu'), ('islam', 'Islam'), ('jewish', 'Jewish'), ('others', 'Others')], max_length=15)),
                ('preference_id_fk', models.OneToOneField(db_column='preference_id_fk', on_delete=django.db.models.deletion.CASCADE, to='authentication.preferences')),
            ],
            options={
                'db_table': 'PreferencesReligion',
            },
        ),
        migrations.CreateModel(
            name='PreferencesRelationship',
            fields=[
                ('preferences_relationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('life partner', 'Life Partner'), ('long-term relationship', 'Long-Term Relationship'), ('short-term relationship', 'Short-Term Relationship'), ('casual', 'Casual')], max_length=25)),
                ('preference_id_fk', models.OneToOneField(db_column='preference_id_fk', on_delete=django.db.models.deletion.CASCADE, to='authentication.preferences')),
            ],
            options={
                'db_table': 'PreferencesRelationship',
            },
        ),
        migrations.CreateModel(
            name='PreferencesPolitics',
            fields=[
                ('preferences_politics_id', models.AutoField(primary_key=True, serialize=False)),
                ('politics_type', models.CharField(choices=[('liberal', 'Liberal'), ('moderate', 'Moderate'), ('conservative', 'Conservative'), ('not political', 'Not Political'), ('other', 'Other')], max_length=20)),
                ('preference_id_fk', models.OneToOneField(db_column='preference_id_fk', on_delete=django.db.models.deletion.CASCADE, to='authentication.preferences')),
            ],
            options={
                'db_table': 'PreferencesPolitics',
            },
        ),
        migrations.CreateModel(
            name='PreferencesLanguage',
            fields=[
                ('preferences_language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_id_fk', models.OneToOneField(db_column='language_id_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.language')),
                ('preference_id_fk', models.OneToOneField(db_column='preference_id_fk', on_delete=django.db.models.deletion.CASCADE, to='authentication.preferences')),
            ],
            options={
                'db_table': 'PreferencesLanguage',
            },
        ),
        migrations.CreateModel(
            name='PreferencesHasKids',
            fields=[
                ('preferences_haskids_id', models.AutoField(primary_key=True, serialize=False)),
                ('has_kids_type', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('preference_id_fk', models.OneToOneField(db_column='preference_id_fk', on_delete=django.db.models.deletion.CASCADE, to='authentication.preferences')),
            ],
            options={
                'db_table': 'PreferencesHasKids',
            },
        ),
        migrations.CreateModel(
            name='PreferencesGender',
            fields=[
                ('preferences_gender_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender_type', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('preference_id_fk', models.OneToOneField(db_column='preference_id_fk', on_delete=django.db.models.deletion.CASCADE, to='authentication.preferences')),
            ],
            options={
                'db_table': 'PreferencesGender',
            },
        ),
        migrations.CreateModel(
            name='PreferencesEthnicity',
            fields=[
                ('preferences_ethnicity_id', models.AutoField(primary_key=True, serialize=False)),
                ('ethnicity_type', models.CharField(choices=[('asian', 'Asian'), ('black', 'Black'), ('hispanic', 'Hispanic'), ('middle eastern', 'Middle Eastern'), ('white', 'White'), ('mixed', 'Mixed'), ('other', 'Other')], max_length=20)),
                ('preference_id_fk', models.OneToOneField(db_column='preference_id_fk', on_delete=django.db.models.deletion.CASCADE, to='authentication.preferences')),
            ],
            options={
                'db_table': 'PreferencesEthnicity',
            },
        ),
        migrations.CreateModel(
            name='PreferencesEducation',
            fields=[
                ('preferences_education_id', models.AutoField(primary_key=True, serialize=False)),
                ('education_level', models.CharField(choices=[('secondary school', 'Secondary School'), ('diploma', 'Diploma'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate')], max_length=20)),
                ('preference_id_fk', models.OneToOneField(db_column='preference_id_fk', on_delete=django.db.models.deletion.CASCADE, to='authentication.preferences')),
            ],
            options={
                'db_table': 'PreferencesEducation',
            },
        ),
        migrations.CreateModel(
            name='PreferencesDrug',
            fields=[
                ('preferences_drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_type', models.CharField(choices=[('yes', 'Yes'), ('sometimes', 'Sometimes'), ('no', 'No')], max_length=10)),
                ('preference_id_fk', models.OneToOneField(db_column='preference_id_fk', on_delete=django.db.models.deletion.CASCADE, to='authentication.preferences')),
            ],
            options={
                'db_table': 'PreferencesDrug',
            },
        ),
        migrations.CreateModel(
            name='PreferencesDrinking',
            fields=[
                ('preferences_drinking_id', models.AutoField(primary_key=True, serialize=False)),
                ('drinking_type', models.CharField(choices=[('yes', 'Yes'), ('sometimes', 'Sometimes'), ('no', 'No')], max_length=10)),
                ('preference_id_fk', models.OneToOneField(db_column='preference_id_fk', on_delete=django.db.models.deletion.CASCADE, to='authentication.preferences')),
            ],
            options={
                'db_table': 'PreferencesDrinking',
            },
        ),
        migrations.CreateModel(
            name='PreferencesBodyType',
            fields=[
                ('preferences_bodytype_id', models.AutoField(primary_key=True, serialize=False)),
                ('body_type_value', models.CharField(choices=[('thin', 'Thin'), ('skinny', 'Skinny'), ('fit', 'Fit'), ('athletic', 'Athletic'), ('jacked', 'Jacked'), ('average', 'Average'), ('curvy', 'Curvy'), ('a little extra', 'A Little Extra'), ('full figured', 'Full Figured'), ('overweight', 'Overweight')], max_length=20)),
                ('preference_id_fk', models.OneToOneField(db_column='preference_id_fk', on_delete=django.db.models.deletion.CASCADE, to='authentication.preferences')),
            ],
            options={
                'db_table': 'PreferencesBodyType',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matched_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('user1_id', models.ForeignKey(db_column='user1_id', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2_id', models.ForeignKey(db_column='user2_id', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Match',
                'unique_together': {('user1_id', 'user2_id')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('like_status', models.CharField(choices=[('liked', 'Liked')], max_length=10)),
                ('liked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('liked_user_id', models.ForeignKey(db_column='liked_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to=settings.AUTH_USER_MODEL)),
                ('liker_user_id', models.ForeignKey(db_column='liker_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Like',
                'unique_together': {('liker_user_id', 'liked_user_id')},
            },
        ),
    ]
