# Generated by Django 4.2.21 on 2025-06-20 06:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('sexual_orientation', models.CharField(blank=True, max_length=8, null=True)),
                ('pronouns', models.CharField(blank=True, max_length=9, null=True)),
                ('height_cm', models.IntegerField(blank=True, null=True)),
                ('body_type', models.CharField(blank=True, max_length=14, null=True)),
                ('education_level', models.CharField(blank=True, max_length=16, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('religion', models.CharField(blank=True, max_length=9, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=14, null=True)),
                ('politics', models.CharField(blank=True, max_length=13, null=True)),
                ('smoking', models.CharField(blank=True, max_length=9, null=True)),
                ('drinking', models.CharField(blank=True, max_length=9, null=True)),
                ('drug_use', models.CharField(blank=True, max_length=9, null=True)),
                ('has_kids', models.IntegerField(blank=True, null=True)),
                ('wants_kids', models.CharField(blank=True, max_length=15, null=True)),
                ('zodiac_sign', models.CharField(blank=True, max_length=11, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
                ('relationship_goals', models.CharField(blank=True, max_length=23, null=True)),
            ],
            options={
                'db_table': 'Profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('image_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ProfileImage',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user1_id', models.UUIDField()),
                ('user2_id', models.UUIDField()),
                ('matched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Match',
                'unique_together': {('user1_id', 'user2_id')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('like_status', models.CharField(choices=[('liked', 'Liked')], max_length=10)),
                ('liked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('liked_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='authentication.user')),
                ('liker_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='authentication.user')),
            ],
            options={
                'db_table': 'Like',
                'unique_together': {('liker_user_id', 'liked_user_id')},
            },
        ),
    ]
