# Generated by Django 5.2.3 on 2025-06-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_pet_profile_profileimage_profilepet_subscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
    ]
